joints:
  shoulder_pan:
    id: 1
    homing_offset: -1363
    range_min: 809
    range_max: 3524
    return_delay_time: 0    
    acceleration: 254

  shoulder_lift:
    id: 2
    homing_offset: -800
    range_min: 790
    range_max: 3168
    return_delay_time: 0   
    acceleration: 254 
  
  elbow_flex:
    id: 3
    homing_offset: 1370
    range_min: 1016
    range_max: 3248
    return_delay_time: 0   
    acceleration: 254

  wrist_flex:
    id: 4
    homing_offset: -1382
    range_min: 759
    range_max: 3128
    return_delay_time: 0   
    acceleration: 254

  wrist_roll:
    id: 5
    homing_offset: -1923
    range_min: 0
    range_max: 4095
    return_delay_time: 0   
    acceleration: 254
  
  gripper:
    id: 6
    homing_offset: 1432
    range_min: 2036
    range_max: 3295
    return_delay_time: 0   
    acceleration: 254